### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by mehditlili** [min2209/dwt#10]
When running main.py as you described in the readme, I get the following error:

> Traceback (most recent call last):
>   File "main.py", line 69, in <module>
>     outputSavePath="../example/output")
>   File "/home/mehdi/Desktop/deeplearning/dwt/E2E/forward.py", line 19, in forward_model
>     model.build(tfBatchImages, tfBatchSS, tfBatchSSMask, keepProb=keepProb)
>   File "/home/mehdi/Desktop/deeplearning/dwt/E2E/e2e_model.py", line 23, in build
>     inputData = tf.concat(3, [inputData, tf.expand_dims(ssMask,-1)])
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1111, in concat
>     dtype=dtypes.int32).get_shape().assert_is_compatible_with(
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 998, in convert_to_tensor
>     as_ref=False)
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 436, in make_tensor_proto
>     _AssertCompatible(values, dtype)
>   File "/home/mehdi/environments/tensorflow-py2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 347, in _AssertCompatible
>     (dtype.name, repr(mismatch), type(mismatch).__name__))
> TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
> 

Am I missing something?

**Comment by qiaoD** [comment]
It's the version of tensflow.Your should change your tensflow version or change your code.

**Comment by mehditlili** [comment]
which version? no specific number is specified in the readme. That would be very appreciated.
I am currently usign 1.10

**Comment by qiaoD** [comment]
I send you my edit code in your email.

**Comment by tiepvupsu** [comment]
> I send you my edit code in your email.

Could you please send me your edit code? 
Thanks.
